language: java

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.gradle

test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)