language: java

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.gradle

test:
  post:
    - if [ -e ./gradlew ]; then ./gradlew jacocoTestReport;else gradle jacocoTestReport;fi
    - bash <(curl -s https://codecov.io/bash)

after_success:
  - bash <(curl -s https://codecov.io/bash)